//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace misechko.com.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Practices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Practices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("misechko.com.Content.Practices", typeof(Practices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;А&lt;/div&gt;
        ///            &lt;h1&gt;Абонентське юридичне обслуговування підприємства&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///        &lt;h2&gt;Місечко та Партнери - Повний спектр юридичних послуг&lt;/h2&gt;
        ///        &lt;p&gt;
        ///            Сучасні економічні та правові реалії нерозривно пов&apos;язують успішне ведення бізнесу з необхідністю якісної юридичної підтримки. Це пов&apos;язано як з зайвим «завзяттям» державних органів на предмет перевірки підприємств, так і з деякими контрагентами, які не [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string abon {
            get {
                return ResourceManager.GetString("abon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;П&lt;/div&gt;
        ///            &lt;h1&gt;Практики&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///        &lt;p&gt;
        ///            Sayenko Kharenko користується відмінною репутацією серед клієнтів за бездоганну якість юридичного супроводу всіх аспектів ведення бізнесу в Україні. Ми забезпечуємо високий рівень консультацій у сферах банківського та фінансового права, конкурентного права, корпоративного права та M&amp;A, міжнародного арбітражу, міжнародної торгівлі, нерухомості, реструктуризації з [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultText {
            get {
                return ResourceManager.GetString("DefaultText", resourceCulture);
            }
        }
    }
}
