//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace misechko.com.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Practices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Practices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("misechko.com.Content.Practices", typeof(Practices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;А&lt;/div&gt;
        ///            &lt;h1&gt;Абонентське юридичне обслуговування підприємства&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///        &lt;h2&gt;Місечко та Партнери - Повний спектр юридичних послуг&lt;/h2&gt;
        ///        &lt;p&gt;
        ///            Сучасні економічні та правові реалії нерозривно пов&apos;язують успішне ведення бізнесу з необхідністю якісної юридичної підтримки. Це пов&apos;язано як з зайвим «завзяттям» державних органів на предмет перевірки підприємств, так і з деякими контрагентами, які не [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string abon {
            get {
                return ResourceManager.GetString("abon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;subblock-headline&quot;&gt;
        ///                &lt;div class=&quot;light-ltr&quot;&gt;П&lt;/div&gt;
        ///                &lt;h1&gt;Публікації&lt;/h1&gt;
        ///            &lt;/div&gt;.
        /// </summary>
        internal static string abon_side {
            get {
                return ResourceManager.GetString("abon_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;Б&lt;/div&gt;
        ///            &lt;h1&gt;Банкрутство&lt;/h1&gt;
        ///&lt;/div&gt;
        ///&lt;p style=&quot;text-align: justify;&quot;&gt;&lt;span&gt;&lt;strong&gt;Місечко та Партнери - Повний спектр юридичних послуг&lt;br&gt;&lt;/strong&gt;&lt;/span&gt;&lt;br&gt;Українська дійсність нерідко призводить до того, що, незважаючи на позитивне рішення суду про стягнення з боржника, в останнього просто може не вистачити коштів для повного погашення боргу. У таких випадках, в українській, так само як і в загальносвітовій практиці, пошире [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bancrupt {
            get {
                return ResourceManager.GetString("bancrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;П&lt;/div&gt;
        ///            &lt;h1&gt;Практики&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///        &lt;p&gt;
        ///            Sayenko Kharenko користується відмінною репутацією серед клієнтів за бездоганну якість юридичного супроводу всіх аспектів ведення бізнесу в Україні. Ми забезпечуємо високий рівень консультацій у сферах банківського та фінансового права, конкурентного права, корпоративного права та M&amp;A, міжнародного арбітражу, міжнародної торгівлі, нерухомості, реструктуризації з [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultText {
            get {
                return ResourceManager.GetString("DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;D&lt;/div&gt;
        ///            &lt;h1&gt;Due Diligence&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///&lt;p style=&quot;text-align: justify;&quot;&gt;Due Diligence - це процедура комплексних юридичних перевірок з метою формування об&apos;єктивного уявлення про об&apos;єкт інвестування, що включає в себе оцінку інвестиційних ризиків, незалежну оцінку об&apos;єкта інвестування, наявних договірних зобов’язань і великої кількості інших факторів.&lt;/p&gt;
        ///&lt;p&gt;&lt;span&gt;Мета процедури Due Diligence - уникнення або максимальне  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diligence {
            get {
                return ResourceManager.GetString("diligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;З&lt;/div&gt;
        ///            &lt;h1&gt;Земля/нерухомість&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;p style=&quot;text-align: justify;&quot;&gt;&lt;span &gt;&lt;strong&gt;&lt;span style=&quot;&quot;&gt;Місечко та Партнери - Повний спектр юридичних послуг&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;br&gt;&lt;br&gt;Дана практика є однією з ключових напрямків діяльності&amp;nbsp;фірми «Місечко та Партнери», тому ми активно розвиваємо практичний досвід у сфері правового супроводу операцій з землею та&amp;nbsp; нерухомістю в процесі купівлі-продажу,&amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string esate {
            get {
                return ResourceManager.GetString("esate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;Б&lt;/div&gt;
        ///            &lt;h1&gt;Банківське та фінансове право&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///&lt;div class=&quot;tabulator&quot;&gt;&lt;/div&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;p style=&quot;text-align: justify;&quot;&gt;&lt;span style=&quot;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;&quot;&gt;Місечко та Партнери - Повний спектр юридичних послуг&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;&lt;/p&gt;
        ///&lt;p style=&quot;text-align: justify;&quot;&gt;Практика у сфері банківського та фінансового права складає досить визначний сектор діяльності фірми «Місечко та Партнери».&lt;/p&gt;
        ///&lt;p style=&quot;text-alig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string finances {
            get {
                return ResourceManager.GetString("finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;/h2&gt;
        ///&lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;Ц&lt;/div&gt;
        ///            &lt;h1&gt;Цінні папери&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///&lt;p align=&quot;justify&quot;&gt;&lt;strong&gt;&lt;span &gt;Місечко та Партнери - Повний спектр юридичних послуг&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p align=&quot;justify&quot;&gt;Юристи, які входять до нашої практики корпоративного права та цінних паперів, консультують як міжнародних, так і місцевих клієнтів по справах, що стосуються зовнішньоекономічних трансакцій та корпоративних і регуляторних питань, надають консультац [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string papers {
            get {
                return ResourceManager.GetString("papers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;practice-headline&quot;&gt;
        ///            &lt;div class=&quot;dark-ltr&quot;&gt;П&lt;/div&gt;
        ///            &lt;h1&gt;Податкова практика&lt;/h1&gt;
        ///        &lt;/div&gt;
        ///&lt;div class=&quot;tabulator&quot;&gt;&lt;/div&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;p style=&quot;text-align: justify;&quot;&gt;&lt;strong&gt;&lt;span &gt;Місечко та Партнери - Повний спектр юридичних послуг&lt;/span&gt;&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p style=&quot;text-align: justify;&quot;&gt;Податкова практика є провідним напрямком діяльності юридичної фірми «Місечко та Партнери». Даною практикою займаються висококласні фахівці в даній галузі, що мають значний успішний досвід  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string taxes {
            get {
                return ResourceManager.GetString("taxes", resourceCulture);
            }
        }
    }
}
