//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace misechko.com.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Publications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Publications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("misechko.com.Content.Publications", typeof(Publications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Зміни в законодавстві щодо іноземного інвестування - стаття Дмитра Жукова для видання &quot;Юрист та Закон&quot; &lt;/h1&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;div style=&quot;text-align: justify;&quot;&gt;17 грудня 2012 року вступає в законну силу Закон України «Про внесення змін до деяких законодавчих актів України щодо державної реєстрації іноземних інвестицій» № 4835-VI, яким запроваджуються зміни до Господарського кодексу України та Закону України «Про режим іноземного інвестування».&amp;nbsp;&lt;br&gt;&lt;br&gt;Ми спробували розглянути, які покращення у сфері інвесту [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inozem_invest {
            get {
                return ResourceManager.GetString("inozem_invest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Нові посади: як підібрати відповідні назви в чинному Класифікаторі - стаття Дмитра Жукова для журналу &quot;Праця і Закон&quot;&lt;/h1&gt;
        ///&lt;div class=&quot;tabulator&quot;&gt;&lt;/div&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;div style=&quot;text-align: justify;&quot;&gt;З 01.11.2010 р. в Україні набрав чинності новий Національний класифікатор професій ДК 003:2010 (Класифікатор), який прийшов на заміну ДК 003:2005. Відтепер кадровим працівникам, так само як і керівникам підприємств, установ та організацій всіх форм власності слід вести кадрову документацію відповідно до нового  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string klasifikator {
            get {
                return ResourceManager.GetString("klasifikator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Що необхідно знати про оформлення нових паспортів? - стаття Володимира Місечко для порталу &quot;Мінфін&quot;&lt;/h1&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;div style=&quot;text-align: justify;&quot;&gt;6 декабря 2012 года вступил в силу Закон Украины «О едином государственном демографическом реестре и документах, которые подтверждают гражданство Украины, удостоверяющих личность или ее специальный статус», который призван урегулировать общественные отношения в сфере и процессе выдачи документов, удостоверяющих личность, подтверждающих гражданство Украины или [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string passport {
            get {
                return ResourceManager.GetString("passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Як отримати гроші від збанкрутілої страхової компанії? - стаття Володимира Місечко для порталу &quot;Мінфін&quot;&lt;/h1&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;div style=&quot;text-align: justify;&quot;&gt;На сегодняшний день в Украине количество страховых компаний уже превышает отметку в 500, многие из которых держат уверенную позицию на рынке страхования. Но как и в любом секторе экономики, не все страховые компании выдерживают конкуренцию, и мы иногда слышим в новостях об обанкротившейся страховой компании.&amp;nbsp;&lt;br&gt;&lt;br&gt;Что же делать, если Ваша страховая [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string waranty_bankrupt {
            get {
                return ResourceManager.GetString("waranty_bankrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Аналіз Закону України &quot;Про зайнятість населення&quot; - стаття Наталії Дейнеги для Юридичної газети &lt;/h1&gt;
        ///&lt;p&gt;&lt;/p&gt;&lt;div style=&quot;text-align: justify;&quot;&gt;З 01 січня 2013 року в силу вступає Закон України «Про зайнятість населення».&amp;nbsp;&lt;br&gt;&lt;br&gt;Враховуючи, що основною метою даного закону є удосконалення механізмів забезпечення державою конституційного права кожної особи на працю, сприяння зайнятості &amp;nbsp;шляхом стимулювання окремих категорій населення, зокрема молоді, до більш активної позиції на ринку праці та с [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zaynyatist {
            get {
                return ResourceManager.GetString("zaynyatist", resourceCulture);
            }
        }
    }
}
